name: EasyDiamonds
main: me.passivepicasso.easydiamonds.EasyDiamonds
version: 0.1
author: By PassivePicasso
description : Minecraft Server mod to allow users to craft a multitude of items previously inaccessible by crafting